
#
# This image is based on another image
#
FROM httpd:2.4

#
# When we create the image, we copy files from the host into
# the image file system. This is NOT a shared folder!
#
COPY ./src/ /usr/local/apache2/htdocs/